# Generated by Django 3.0.2 on 2020-01-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('username',)},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
