# Generated by Django 3.0.2 on 2020-01-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='c2bpayments',
            old_name='bill_ref_number',
            new_name='BillRefNumber',
        ),
        migrations.RenameField(
            model_name='c2bpayments',
            old_name='business_short_code',
            new_name='BusinessShortCode',
        ),
        migrations.RenameField(
            model_name='c2bpayments',
            old_name='first_name',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='c2bpayments',
            old_name='invoice_number',
            new_name='InvoiceNumber',
        ),
        migrations.RenameField(
            model_name='c2bpayments',
            old_name='last_name',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='c2bpayments',
            old_name='phone_number',
            new_name='MSISDN',
        ),
        migrations.RenameField(
            model_name='c2bpayments',
            old_name='middle_name',
            new_name='MiddleName',
        ),
        migrations.RenameField(
            model_name='c2bpayments',
            old_name='org_account_balance',
            new_name='OrgAccountBalance',
        ),
        migrations.RenameField(
            model_name='c2bpayments',
            old_name='third_party_transaction_id',
            new_name='ThirdPartyTransID',
        ),
        migrations.RenameField(
            model_name='c2bpayments',
            old_name='transaction_amount',
            new_name='TransAmount',
        ),
        migrations.RenameField(
            model_name='c2bpayments',
            old_name='transaction_id',
            new_name='TransID',
        ),
        migrations.RenameField(
            model_name='c2bpayments',
            old_name='transaction_time',
            new_name='TransTime',
        ),
        migrations.RenameField(
            model_name='c2bpayments',
            old_name='transaction_type',
            new_name='TransactionType',
        ),
    ]
